[package]
name = "alea"
version = "0.1.0"
edition = "2021"
description = "A flexible random number generation library"
license = "MIT"
repository = "https://github.com/SkuldNorniern/alea"

[lib]
name = "alea"
path = "src/lib.rs"

[dependencies]
